version: 0.2

env:    
  variables:      
    AWS_DEFAULT_REGION: "MENTION YOUR REGION"
    AWS_ACCOUNT_ID: "MENTION YOUR ACCOUNT ID"
    IMAGE_REPO_NAME: "MENTION YOUR ECR REPO NAME"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - sudo apt-get update -y && apt-get install jq -y
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - tmp=$(mktemp) && SHA=$(docker inspect YOURREPONAME:latest | jq -c '.[0].RepoDigests' | sed 's/[][]//g' | sed 's/"//g') && jq -r --arg SHA "$SHA" '.Resources.TaskDefinition1.Properties.ContainerDefinitions[0].Image=$SHA' ecs-taskdefinition-service.json > "$tmp" && mv -f "$tmp" ecs-taskdefinition-service.json
artifacts: 
  files: 
    - ecs-taskdefinition-service.json
  discard-paths: yes  
